export const Users = [
  {
    id: '635d12715436602ce34008cc',
    index: 0,
    guid: '31558be5-78f6-40d6-8c35-c94ebf36da99',
    isActive: true,
    balance: '$3,231.25',
    picture: 'http://placehold.it/32x32',
    age: 28,
    eyeColor: 'brown',
    name: 'Michelle Leonard',
    gender: 'female',
    company: 'DOGNOST',
    email: 'michelleleonard@dognost.com',
    phone: '+1 (982) 422-2350',
    address: '722 Cozine Avenue, Salix, Mississippi, 5161',
    about:
      'Incididunt sint tempor excepteur esse sunt cillum ad est minim ut. Exercitation non fugiat mollit adipisicing veniam quis adipisicing quis irure ea. Ullamco adipisicing commodo dolore quis deserunt. Dolor occaecat quis aliqua ipsum esse.\r\n',
    registered: '2017-08-06T02:49:45 -02:00',
    latitude: -30.307195,
    longitude: 59.913567,
    tags: ['veniam', 'incididunt', 'nostrud', 'minim', 'aliqua'],
    friends: [
      {
        id: 0,
        name: 'Mullen Villarreal',
      },
      {
        id: 1,
        name: 'Villarreal Lucas',
      },
      {
        id: 2,
        name: 'Joann Bradford',
      },
    ],
    greeting: 'Hello, Michelle Leonard! You have 2 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    id: '635d127121b61c9f7e0a21b5',
    index: 1,
    guid: '464e619d-b3ea-4a13-826c-21474beda672',
    isActive: false,
    balance: '$2,245.66',
    picture: 'http://placehold.it/32x32',
    age: 22,
    eyeColor: 'blue',
    name: 'Tyler Mcdaniel',
    company: 'OTHERWAY',
    email: 'tylermcdaniel@otherway.com',
    phone: '+1 (992) 595-3884',
    address: '131 Ford Street, Catharine, Arkansas, 8136',
    about:
      'Non ut elit minim quis pariatur nisi. Duis nostrud ex sunt irure officia ipsum tempor adipisicing. Officia anim sit consequat enim in. Adipisicing ut dolor amet fugiat in occaecat. Labore aliquip nostrud mollit nisi et ipsum fugiat reprehenderit. Enim deserunt qui duis laborum. Nisi consectetur ad minim duis officia commodo laboris mollit aliqua eu eu.\r\n',
    registered: '2018-12-20T11:06:19 -01:00',
    latitude: -54.430202,
    longitude: 17.101944,
    tags: [
      'tempor',
      'voluptate',
      'ullamco',
      'exercitation',
      'et',
      'ad',
      'cillum',
    ],
    friends: [
      {
        id: 0,
        name: 'Brennan Barnett',
      },
      {
        id: 1,
        name: 'Sophie Ramsey',
      },
      {
        id: 2,
        name: 'Decker Pope',
      },
    ],
    greeting: 'Hello, Tyler Mcdaniel! You have 10 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    id: '635d1271e2847edeab55ac16',
    index: 2,
    guid: 'cf7fdc4f-4e54-4a82-9869-3a803807f718',
    isActive: true,
    balance: '$3,955.21',
    picture: 'http://placehold.it/32x32',
    age: 33,
    eyeColor: 'green',
    name: 'Eugenia Rasmussen',
    gender: 'female',
    company: 'ASSISTIA',
    email: 'eugeniarasmussen@assistia.com',
    phone: '+1 (818) 555-3045',
    address: '225 Schenck Court, Loyalhanna, Florida, 5214',
    about:
      'Laborum culpa dolore culpa cillum deserunt irure minim. Dolore quis veniam ea labore ipsum tempor sint excepteur irure quis cupidatat. Exercitation consequat magna mollit consectetur voluptate labore cillum adipisicing sint Lorem. Ullamco ex fugiat dolor in amet non proident id.\r\n',
    registered: '2016-10-11T01:36:38 -02:00',
    latitude: 47.689932,
    longitude: 61.759739,
    tags: ['aute', 'ea', 'excepteur', 'velit', 'fugiat', 'eiusmod', 'esse'],
    friends: [
      {
        id: 0,
        name: 'Lilia Farley',
      },
      {
        id: 1,
        name: 'Bernadette Odonnell',
      },
      {
        id: 2,
        name: 'Walls Brewer',
      },
    ],
    greeting: 'Hello, Eugenia Rasmussen! You have 10 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    id: '635d12711ca19dcfdf7526ae',
    index: 3,
    guid: '2deaafd8-4c0c-4b98-aa70-2d25c35ddf5f',
    isActive: true,
    balance: '$2,322.65',
    picture: 'http://placehold.it/32x32',
    age: 31,
    eyeColor: 'brown',
    name: 'Cecile Bowen',
    gender: 'female',
    company: 'FIBRODYNE',
    phone: '+1 (809) 438-2861',
    address: '492 Aviation Road, Galesville, Hawaii, 5765',
    about:
      'Culpa tempor deserunt aliquip labore fugiat anim commodo. Velit sunt aliquip reprehenderit in. Amet incididunt id laboris aliqua qui sit velit elit deserunt nisi.\r\n',
    registered: '2014-12-31T04:22:48 -01:00',
    latitude: -37.901975,
    longitude: -154.07586,
    tags: ['aliquip', 'est', 'magna', 'aute', 'anim', 'fugiat', 'nulla'],
    friends: [
      {
        id: 0,
        name: 'Lucinda Ballard',
      },
      {
        id: 1,
        name: 'Marisa Weeks',
      },
      {
        id: 2,
        name: 'Velasquez Walton',
      },
    ],
    greeting: 'Hello, Cecile Bowen! You have 1 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    id: '635d12717a79af4c13171143',
    index: 4,
    guid: '0a305ead-0c61-4625-a589-bea78efb1500',
    isActive: true,
    balance: '$2,088.33',
    picture: 'http://placehold.it/32x32',
    age: 31,
    eyeColor: 'green',
    name: 'Stacy Parks',
    gender: 'female',
    company: 'SCENTRIC',
    email: 'stacyparks@scentric.com',
    phone: '+1 (983) 470-3837',
    address: '167 Cumberland Street, Juntura, New Hampshire, 6829',
    about:
      'Reprehenderit ut do ad culpa tempor esse sunt anim reprehenderit ex incididunt consequat. Culpa laborum excepteur excepteur laborum do Lorem pariatur nulla elit dolor laboris et sint sunt. Nisi elit et dolor voluptate aliquip qui dolore voluptate sunt excepteur est consequat. Duis magna amet in laborum mollit cupidatat aliqua labore mollit ea.\r\n',
    registered: '2014-03-25T02:24:44 -01:00',
    latitude: -55.716682,
    longitude: 88.84972,
    tags: ['deserunt', 'veniam', 'sint', 'minim', 'non', 'culpa', 'proident'],
    friends: [
      {
        id: 0,
        name: 'Soto Huffman',
      },
      {
        id: 1,
        name: 'Tammy Riddle',
      },
      {
        id: 2,
        name: 'Allen Wood',
      },
    ],
    greeting: 'Hello, Stacy Parks! You have 9 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    id: '635d12710447db13b03f0c41',
    index: 5,
    guid: '4614a512-355a-4da1-bf94-98c3d27116c9',
    isActive: false,
    balance: '$1,777.39',
    picture: 'http://placehold.it/32x32',
    age: 23,
    eyeColor: 'blue',
    name: 'Hazel Eaton',
    gender: 'female',
    company: 'TRIPSCH',
    email: 'hazeleaton@tripsch.com',
    phone: '+1 (911) 586-2419',
    address: '842 Osborn Street, Yardville, Connecticut, 4964',
    about:
      'Velit qui magna esse nisi quis. Velit adipisicing in eu culpa pariatur ad Lorem veniam dolore excepteur adipisicing. Tempor esse mollit veniam fugiat enim commodo exercitation ut culpa. Laboris ex pariatur reprehenderit esse veniam minim commodo laboris ipsum eiusmod duis. Culpa fugiat reprehenderit labore labore non ipsum.\r\n',
    registered: '2015-03-10T01:00:09 -01:00',
    latitude: -59.938564,
    longitude: -51.2037,
    tags: [
      'Lorem',
      'nostrud',
      'incididunt',
      'excepteur',
      'ea',
      'consequat',
      'ad',
    ],
    friends: [
      {
        id: 0,
        name: 'Chris Cummings',
      },
      {
        id: 1,
        name: 'Spencer Whitehead',
      },
      {
        id: 2,
        name: 'Schmidt Bray',
      },
    ],
    greeting: 'Hello, Hazel Eaton! You have 10 unread messages.',
    favoriteFruit: 'apple',
  },
];
